In [1]:
import os
import re
import _pickle as cPickle
from collections import OrderedDict, defaultdict, Counter

import matplotlib
%matplotlib inline
import matplotlib.pyplot as plt

import numpy as np
import pandas as pd
import tensorflow as tf
from sklearn.feature_extraction.text import TfidfVectorizer
from nltk import word_tokenize

from data_structure import Instance

# load data

In [20]:
path_data = '/home/m-isonuma/treetglm/data/yelp/yelp_df.pkl'
train_df, dev_df, test_df, word_to_idx, idx_to_word, bow_idxs = cPickle.load(open(path_data, 'rb'))

In [21]:
len(bow_idxs)

6177

# write data

In [22]:
train_df

,business_id,doc_l,sent_l,max_sent_l,bows,token_idxs,doc_bow
0,--FBCX-N37CMYDfs790Bnw,40,"[12, 24, 7, 3, 20, 5, 9, 14, 21, 17, 26, 7, 19...",37,"(0, 220)\t1\n (0, 266)\t1\n (0, 1415)\t1\n...","[[20, 101, 149, 554, 9, 609, 1881, 5, 26, 49, ...","[0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, ..."
1,--FBCX-N37CMYDfs790Bnw,45,"[5, 15, 12, 29, 4, 7, 4, 15, 10, 3, 9, 4, 5, 6...",29,"(1, 55)\t1\n (1, 93)\t1\n (1, 750)\t1\n (...","[[27, 24, 7, 87, 73], [111, 15, 13, 133, 5, 19...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
2,--FBCX-N37CMYDfs790Bnw,38,"[8, 7, 14, 4, 7, 9, 18, 13, 18, 8, 5, 18, 7, 1...",31,"(0, 369)\t1\n (0, 758)\t1\n (1, 753)\t1\n ...","[[12, 10, 8, 1164, 734, 15, 4, 96], [1210, 14,...","[0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, ..."
3,--FBCX-N37CMYDfs790Bnw,38,"[4, 4, 22, 6, 31, 7, 9, 9, 7, 3, 5, 6, 6, 3, 7...",31,"(1, 2812)\t1\n (2, 129)\t1\n (2, 266)\t1\n...","[[20, 31, 36, 15727], [5, 20, 37, 3336], [379,...","[0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, ..."
4,--FBCX-N37CMYDfs790Bnw,48,"[7, 5, 7, 9, 20, 4, 26, 12, 10, 6, 9, 12, 11, ...",36,"(0, 3)\t1\n (2, 21)\t1\n (2, 296)\t1\n (2...","[[20, 75, 65, 199, 40, 13, 245], [4, 73, 11, 6...","[0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, ..."
...,...,...,...,...,...,...,...
185491,zzwicjPC9g246MK2M1ZFBA,48,"[9, 5, 7, 6, 4, 12, 6, 4, 3, 4, 8, 5, 12, 10, ...",30,"(0, 40)\t1\n (0, 121)\t1\n (0, 624)\t1\n ...","[[13105, 11, 1015, 28, 13, 70, 427, 314, 185],...","[0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 2, ..."
185492,zzwicjPC9g246MK2M1ZFBA,47,"[3, 9, 4, 6, 14, 5, 6, 7, 10, 8, 9, 30, 7, 21,...",32,"(1, 2149)\t1\n (1, 2167)\t1\n (1, 3075)\t1...","[[13105, 11, 28], [3610, 161, 137, 23, 4, 2671...","[0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, ..."
185493,zzwicjPC9g246MK2M1ZFBA,47,"[4, 13, 6, 9, 5, 7, 6, 5, 14, 4, 17, 5, 19, 31...",31,"(1, 138)\t1\n (3, 40)\t1\n (3, 121)\t1\n ...","[[8, 36, 148, 96], [68, 447, 7, 8, 27, 161, 13...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 2, 0, 0, 1, ..."
185494,zzwicjPC9g246MK2M1ZFBA,50,"[9, 4, 4, 8, 6, 3, 4, 3, 5, 15, 6, 5, 4, 12, 1...",32,"(0, 247)\t1\n (0, 545)\t1\n (0, 815)\t1\n ...","[[1226, 168, 930, 222, 51, 2267, 182, 588, 179...","[0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, ..."
185495,zzwicjPC9g246MK2M1ZFBA,48,"[18, 6, 19, 8, 13, 9, 30, 7, 21, 7, 4, 21, 12,...",30,"(0, 25)\t1\n (0, 166)\t1\n (0, 209)\t1\n ...","[[363, 19, 234, 96, 690, 481, 159, 148, 5, 518...","[0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, ..."

In [23]:
def prepare_instances(data_df):
    instances = []
    for idx_doc, doc in data_df.iterrows():
        instance = Instance()
        instance.idx = idx_doc
        instance.bow = doc.doc_bow
        instances.append(instance)
    return instances

In [24]:
instances_train = prepare_instances(train_df)
instances_dev = prepare_instances(dev_df)
instances_test = prepare_instances(test_df)

In [25]:
path_output = '/home/m-isonuma/tsntm/data/yelp/instances.pkl'
cPickle.dump((instances_train, instances_dev, instances_test, word_to_idx, idx_to_word, bow_idxs),open(path_output,'wb'))